//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BlogModel", "FK_Pieces_Artists", "Artists", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MosArt.Models.Artist), "Pieces", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MosArt.Models.Piece), true)]
[assembly: EdmRelationshipAttribute("BlogModel", "FK_Pieces_Pieces", "Pieces", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MosArt.Models.Piece), "Pieces1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MosArt.Models.Piece), true)]
[assembly: EdmRelationshipAttribute("BlogModel", "FK_Pieces_Pieces1", "Pieces", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MosArt.Models.Piece), "Pieces1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MosArt.Models.Piece), true)]

#endregion

namespace MosArt.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlogEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlogEntities object using the connection string found in the 'BlogEntities' section of the application configuration file.
        /// </summary>
        public BlogEntities() : base("name=BlogEntities", "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogEntities object.
        /// </summary>
        public BlogEntities(string connectionString) : base(connectionString, "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogEntities object.
        /// </summary>
        public BlogEntities(EntityConnection connection) : base(connection, "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Artist> Artists
        {
            get
            {
                if ((_Artists == null))
                {
                    _Artists = base.CreateObjectSet<Artist>("Artists");
                }
                return _Artists;
            }
        }
        private ObjectSet<Artist> _Artists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Piece> Pieces
        {
            get
            {
                if ((_Pieces == null))
                {
                    _Pieces = base.CreateObjectSet<Piece>("Pieces");
                }
                return _Pieces;
            }
        }
        private ObjectSet<Piece> _Pieces;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Artists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArtists(Artist artist)
        {
            base.AddObject("Artists", artist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pieces EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPieces(Piece piece)
        {
            base.AddObject("Pieces", piece);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Artist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Artist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Artist object.
        /// </summary>
        /// <param name="artistID">Initial value of the ArtistID property.</param>
        public static Artist CreateArtist(global::System.Int32 artistID)
        {
            Artist artist = new Artist();
            artist.ArtistID = artistID;
            return artist;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArtistID
        {
            get
            {
                return _ArtistID;
            }
            set
            {
                if (_ArtistID != value)
                {
                    OnArtistIDChanging(value);
                    ReportPropertyChanging("ArtistID");
                    _ArtistID = StructuralObject.SetValidValue(value, "ArtistID");
                    ReportPropertyChanged("ArtistID");
                    OnArtistIDChanged();
                }
            }
        }
        private global::System.Int32 _ArtistID;
        partial void OnArtistIDChanging(global::System.Int32 value);
        partial void OnArtistIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true, "ImageURL");
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArtistStyle
        {
            get
            {
                return _ArtistStyle;
            }
            set
            {
                OnArtistStyleChanging(value);
                ReportPropertyChanging("ArtistStyle");
                _ArtistStyle = StructuralObject.SetValidValue(value, true, "ArtistStyle");
                ReportPropertyChanged("ArtistStyle");
                OnArtistStyleChanged();
            }
        }
        private global::System.String _ArtistStyle;
        partial void OnArtistStyleChanging(global::System.String value);
        partial void OnArtistStyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowContent
        {
            get
            {
                return _AllowContent;
            }
            set
            {
                OnAllowContentChanging(value);
                ReportPropertyChanging("AllowContent");
                _AllowContent = StructuralObject.SetValidValue(value, "AllowContent");
                ReportPropertyChanged("AllowContent");
                OnAllowContentChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowContent;
        partial void OnAllowContentChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowContentChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Artists", "Pieces")]
        public EntityCollection<Piece> Pieces
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Piece>("BlogModel.FK_Pieces_Artists", "Pieces");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Piece>("BlogModel.FK_Pieces_Artists", "Pieces", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Piece")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Piece : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Piece object.
        /// </summary>
        /// <param name="pieceID">Initial value of the PieceID property.</param>
        /// <param name="artistID">Initial value of the ArtistID property.</param>
        public static Piece CreatePiece(global::System.Int32 pieceID, global::System.Int32 artistID)
        {
            Piece piece = new Piece();
            piece.PieceID = pieceID;
            piece.ArtistID = artistID;
            return piece;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PieceID
        {
            get
            {
                return _PieceID;
            }
            set
            {
                if (_PieceID != value)
                {
                    OnPieceIDChanging(value);
                    ReportPropertyChanging("PieceID");
                    _PieceID = StructuralObject.SetValidValue(value, "PieceID");
                    ReportPropertyChanged("PieceID");
                    OnPieceIDChanged();
                }
            }
        }
        private global::System.Int32 _PieceID;
        partial void OnPieceIDChanging(global::System.Int32 value);
        partial void OnPieceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArtistID
        {
            get
            {
                return _ArtistID;
            }
            set
            {
                OnArtistIDChanging(value);
                ReportPropertyChanging("ArtistID");
                _ArtistID = StructuralObject.SetValidValue(value, "ArtistID");
                ReportPropertyChanged("ArtistID");
                OnArtistIDChanged();
            }
        }
        private global::System.Int32 _ArtistID;
        partial void OnArtistIDChanging(global::System.Int32 value);
        partial void OnArtistIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Medium
        {
            get
            {
                return _Medium;
            }
            set
            {
                OnMediumChanging(value);
                ReportPropertyChanging("Medium");
                _Medium = StructuralObject.SetValidValue(value, true, "Medium");
                ReportPropertyChanged("Medium");
                OnMediumChanged();
            }
        }
        private global::System.String _Medium;
        partial void OnMediumChanging(global::System.String value);
        partial void OnMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Artists", "Artists")]
        public Artist Artist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Artist>("BlogModel.FK_Pieces_Artists", "Artists").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Artist>("BlogModel.FK_Pieces_Artists", "Artists").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Artist> ArtistReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Artist>("BlogModel.FK_Pieces_Artists", "Artists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Artist>("BlogModel.FK_Pieces_Artists", "Artists", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Pieces", "Pieces1")]
        public Piece Pieces1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Piece> Pieces1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Pieces", "Pieces")]
        public Piece Piece1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Piece> Piece1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces", "Pieces", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Pieces1", "Pieces1")]
        public Piece Pieces11
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Piece> Pieces11Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Pieces_Pieces1", "Pieces")]
        public Piece Piece2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Piece> Piece2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Piece>("BlogModel.FK_Pieces_Pieces1", "Pieces", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
