//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Pieces = new HashSet<Piece>();
        }
    
        public int ArtistID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ImageURL { get; set; }
        public string ArtistStyle { get; set; }
        public string Username { get; set; }
        public Nullable<bool> AllowContent { get; set; }
    
        public virtual ICollection<Piece> Pieces { get; set; }
    }
}
