//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int PieceID { get; set; }
        public int ArtistID { get; set; }
        public string Title { get; set; }
        public string Medium { get; set; }
        public string Description { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
